package com.bookshop.BookShopApp.structure.user;

import com.bookshop.BookShopApp.structure.enums.ContactType;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "user_contact")
@ApiModel(description = "entity representing a user contacts")
public class UserContact {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("user contact id generated by db automatically")
    private int id;

    @Column(name="user_id", columnDefinition = "INT NOT NULL")
    @ApiModelProperty("user id from table users")
    private int userId;

    @ApiModelProperty("contact type (PHONE or EMAIL)")
    private ContactType type;

    @Column(columnDefinition = "SMALLINT NOT NULL")
    @ApiModelProperty("is contact approved (0 or 1)")
    private short approved;

    @Column(columnDefinition = "VARCHAR(255)")
    @ApiModelProperty("contact verification code")
    private String code;

    @Column(columnDefinition = "INT")
    @ApiModelProperty("number of attempts to enter a verification code")
    private int codeTrails;

    @Column(columnDefinition = "TIMESTAMP")
    @ApiModelProperty("date and time verification code generation")
    private LocalDateTime codeTime;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("contact (e-mai or phone number)")
    private String contact;

    @ManyToOne
    @JsonIgnore
    @JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
    private User contactUser;

    public User getContactUser() {
        return contactUser;
    }

    public void setContactUser(User contactUser) {
        this.contactUser = contactUser;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public ContactType getType() {
        return type;
    }

    public void setType(ContactType type) {
        this.type = type;
    }

    public short getApproved() {
        return approved;
    }

    public void setApproved(short approved) {
        this.approved = approved;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public int getCodeTrails() {
        return codeTrails;
    }

    public void setCodeTrails(int codeTrails) {
        this.codeTrails = codeTrails;
    }

    public LocalDateTime getCodeTime() {
        return codeTime;
    }

    public void setCodeTime(LocalDateTime codeTime) {
        this.codeTime = codeTime;
    }

    public String getContact() {
        return contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }
}
