package com.bookshop.BookShopApp.structure.other;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;

@Entity
@Table(name = "faq")
@ApiModel(description = "entity representing a faq")
public class Faq {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("faq id generated by db automatically")
    private int id;

    @Column(columnDefinition = "INT NOT NULL  DEFAULT 0")
    @ApiModelProperty("faq serial number")
    private int sortIndex;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("faq question")
    private String question;

    @Column(columnDefinition = "TEXT NOT NULL")
    @ApiModelProperty("faq answer")
    private String answer;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getSortIndex() {
        return sortIndex;
    }

    public void setSortIndex(int sortIndex) {
        this.sortIndex = sortIndex;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }
}
