package com.bookshop.BookShopApp.structure.book.file;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.util.List;

@Entity
@Table(name = "book_file_type")
@ApiModel(description = "entity representing a book file type")
public class BookFileType {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("file type id generated by db automatically")
    private int id;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("file type name (PDF, EPUB, FB2)")
    private String name;

    @Column(columnDefinition = "TEXT")
    @ApiModelProperty("file type description")
    private String description;

    @OneToMany(mappedBy = "fileType")
    @JsonIgnore
    private List<BookFile> files;

    public String getExtensionStringByTypeID(Integer typeId){
        switch (typeId){
            case 1:return ".pdf";
            case 2:return ".epub";
            case 3:return ".fb2";
            default:return "";
        }
    }


    public List<BookFile> getFiles() {
        return files;
    }

    public void setFiles(List<BookFile> files) {
        this.files = files;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
