package com.bookshop.BookShopApp.structure.payments;

import com.bookshop.BookShopApp.structure.book.Book;
import com.bookshop.BookShopApp.structure.user.User;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "balance_transaction")
@ApiModel(description = "entity representing a transactions by user accounts")
public class BalanceTransaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("transaction id generated by db automatically")
    private int id;

    @Column(name="user_id", columnDefinition = "INT NOT NULL")
    @ApiModelProperty("user id fromtable users")
    private int userId;

    @Column(columnDefinition = "TIMESTAMP NOT NULL")
    @ApiModelProperty("transaction date and time")
    private LocalDateTime time;

    @Column(columnDefinition = "INT NOT NULL  DEFAULT 0")
    @ApiModelProperty("transaction value ( > 0 Credit, < 0 Debit)")
    private int value;

    @Column(name="book_id")
    @ApiModelProperty("transaction book id from table books")
    private int bookId;

    @Column(columnDefinition = "TEXT NOT NULL")
    @ApiModelProperty("transaction description")
    private String description;

    @ApiModelProperty("Is transaction confirmed")
    private int confirmed;

    @ApiModelProperty("Referer Url")
    private String referer;


    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
    @JsonIgnore
    private User transactionUser;

    public User getTransactionUser() {
        return transactionUser;
    }

    public void setTransactionUser(User transactionUser) {
        this.transactionUser = transactionUser;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public LocalDateTime getTime() {
        return time;
    }

    public void setTime(LocalDateTime time) {
        this.time = time;
    }

    public int getValue() {
        return value;
    }

    public void setValue(int value) {
        this.value = value;
    }

    public int getBookId() {
        return bookId;
    }

    public void setBookId(int bookId) {
        this.bookId = bookId;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getConfirmed() {
        return confirmed;
    }

    public void setConfirmed(int confirmed) {
        this.confirmed = confirmed;
    }

    public String getReferer() {
        return referer;
    }

    public void setReferer(String referer) {
        this.referer = referer;
    }
}
