package com.bookshop.BookShopApp.structure.book.links;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "book2user")
@ApiModel(description = "entity representing connections books and users")
public class Book2User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("connection id generated by db automatically")
    private int id;

    @Column(columnDefinition = "TIMESTAMP NOT NULL")
    @ApiModelProperty("date and time connection generation")
    private LocalDateTime time;

    @Column(name="type_id", columnDefinition = "INT NOT NULL")
    @ApiModelProperty("type connection from table book2user_type")
    private int typeId;

    @Column(name="book_id", columnDefinition = "INT NOT NULL")
    @ApiModelProperty("book id from table books")
    private int bookId;

    @Column(name="user_id", columnDefinition = "INT NOT NULL")
    @ApiModelProperty("user id from table users")
    private int userId;

    @ManyToOne
    @JoinColumn(name = "type_id", nullable = false, insertable = false, updatable = false)
    @JsonIgnore
    private Book2UserType typeUserConnection;

    public Book2UserType getTypeUserConnection() {
        return typeUserConnection;
    }

    public void setTypeUserConnection(Book2UserType typeUserConnection) {
        this.typeUserConnection = typeUserConnection;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public LocalDateTime getTime() {
        return time;
    }

    public void setTime(LocalDateTime time) {
        this.time = time;
    }

    public int getTypeId() {
        return typeId;
    }

    public void setTypeId(int typeId) {
        this.typeId = typeId;
    }

    public int getBookId() {
        return bookId;
    }

    public void setBookId(int bookId) {
        this.bookId = bookId;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }
}
