package com.bookshop.BookShopApp.structure.book.links;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;

@Entity
@Table(name = "book2genre")
@ApiModel(description = "Connections books and genres")
public class Book2Genre {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("connection id generated by db automatically")
    private int id;

    @Column(name="book_id", columnDefinition = "INT NOT NULL")
    @ApiModelProperty("id book from table books")
    private int bookId;

    @Column(name="genre_id", columnDefinition = "INT NOT NULL")
    @ApiModelProperty("id genre from table genres")
    private int genreId;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getBookId() {
        return bookId;
    }

    public void setBookId(int bookId) {
        this.bookId = bookId;
    }

    public int getGenreId() {
        return genreId;
    }

    public void setGenreId(int genreId) {
        this.genreId = genreId;
    }
}
