package com.bookshop.BookShopApp.structure.book.links;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.persistence.*;
import java.util.List;

@Entity
@Table(name = "book2user_type")
@ApiModel(description = "entity representing types connection books and authors")
public class Book2UserType {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id type connection generated by db automatically")
    private int id;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("connection type code (KEPT, CART, PAID, ARCHIVED)")
    private String code;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("connection type name (PostponesT, InCart, Paid, In archive)")
    private String name;

    @OneToMany(mappedBy = "typeUserConnection")
    private List<Book2User> connectionsBooksUsers;

    public List<Book2User> getConnectionsBooksUsers() {
        return connectionsBooksUsers;
    }

    public void setConnectionsBooksUsers(List<Book2User> connectionsBooksUsers) {
        this.connectionsBooksUsers = connectionsBooksUsers;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
