package com.bookshop.BookShopApp.structure.book.links;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;

@Entity
@Table(name = "book2author")
@ApiModel(description = "entity representing connections books and authors")
public class Book2Author {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id connection generated by db automatically")
    private int id;

    @Column(name="book_id", columnDefinition = "INT NOT NULL")
    @ApiModelProperty("connection id from table books")
    private int bookId;

    @Column(name="author_id", columnDefinition = "INT NOT NULL")
    @ApiModelProperty("id author from table authors")
    private int authorId;

    @Column(columnDefinition = "INT NOT NULL  DEFAULT 0")
    @ApiModelProperty("author's serial number ")
    private int sortIndex;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getBookId() {
        return bookId;
    }

    public void setBookId(int bookId) {
        this.bookId = bookId;
    }

    public int getAuthorId() {
        return authorId;
    }

    public void setAuthorId(int authorId) {
        this.authorId = authorId;
    }

    public int getSortIndex() {
        return sortIndex;
    }

    public void setSortIndex(int sortIndex) {
        this.sortIndex = sortIndex;
    }
}
