package com.bookshop.BookShopApp.structure.book.review;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "book_review_like")
@ApiModel(description = "Books review like and dislike")
public class BookReviewLike {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id like/dislike generated by db automatically")
    private int id;

    @Column(name="review_id", columnDefinition = "INT NOT NULL")
    @ApiModelProperty("id review from table book_review")
    private int reviewId;

    @Column(name="user_id", columnDefinition = "INT NOT NULL")
    @ApiModelProperty("id like/dislike user from table users")
    private int userId;

    @Column(columnDefinition = "TIMESTAMP NOT NULL")
    @ApiModelProperty("like/dislike time (format TIMESTAMP)")
    private LocalDateTime time;

    @Column(columnDefinition = "SMALLINT NOT NULL")
    @ApiModelProperty("like or dislike (format 1 or -1)")
    private short value;

    @ManyToOne
    @JoinColumn(name = "review_id", nullable = false, insertable = false, updatable = false)
    @JsonIgnore
    private BookReview likeReview;

    public BookReview getLikeReview() {
        return likeReview;
    }

    public void setLikeReview(BookReview likeReview) {
        this.likeReview = likeReview;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getReviewId() {
        return reviewId;
    }

    public void setReviewId(int reviewId) {
        this.reviewId = reviewId;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public LocalDateTime getTime() {
        return time;
    }

    public void setTime(LocalDateTime time) {
        this.time = time;
    }

    public short getValue() {
        return value;
    }

    public void setValue(short value) {
        this.value = value;
    }
}
