package com.bookshop.BookShopApp.structure.book.review;

import com.bookshop.BookShopApp.structure.book.Book;
import com.bookshop.BookShopApp.structure.user.User;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "book_score")
@ApiModel(description = "Books scores")
public class BookScore {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("score id generated by db automatically")
    private int id;

    @Column(name="book_id", columnDefinition = "INT NOT NULL")
    @ApiModelProperty("id book from table books")
    private int bookId;

    @Column(name="user_id", columnDefinition = "INT NOT NULL")
    @ApiModelProperty("score user id from table users")
    private int userId;

    @Column(columnDefinition = "TIMESTAMP NOT NULL")
    @ApiModelProperty("score time (format TIMESTAMP)")
    private LocalDateTime time;

    @Column(columnDefinition = "SMALLINT NOT NULL")
    @ApiModelProperty("book score from 1 to 5")
    private int score;

    @ManyToOne
    @JoinColumn(name = "book_id", nullable = false, insertable = false, updatable = false)
    @JsonIgnore
    private Book scoreBook;

    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
    @JsonIgnore
    private User scoreUser;

    public Book getScoreBook() {
        return scoreBook;
    }

    public void setScoreBook(Book scoreBook) {
        this.scoreBook = scoreBook;
    }

    public User getScoreUser() {
        return scoreUser;
    }

    public void setScoreUser(User scoreUser) {
        this.scoreUser = scoreUser;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getBookId() {
        return bookId;
    }

    public void setBookId(int bookId) {
        this.bookId = bookId;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public LocalDateTime getTime() {
        return time;
    }

    public void setTime(LocalDateTime time) {
        this.time = time;
    }

    public int getScore() {
        return score;
    }

    public void setScore(int score) {
        this.score = score;
    }
}
