package com.bookshop.BookShopApp.structure.book.review;

import com.bookshop.BookShopApp.structure.book.Book;
import com.bookshop.BookShopApp.structure.user.User;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.persistence.*;
import java.time.LocalDateTime;
import java.util.List;

@Entity
@Table(name = "book_review")
@ApiModel(description = "Books reviews")
public class BookReview {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("review id generated by db automatically")
    private int id;

    @Column(name="book_id", columnDefinition = "INT NOT NULL")
    @ApiModelProperty("id book from table books")
    private int bookId;

    @Column(name="user_id", columnDefinition = "INT NOT NULL")
    @ApiModelProperty("review user id from table users")
    private int userId;

    @Column(columnDefinition = "TIMESTAMP NOT NULL")
    @ApiModelProperty("review time (format TIMESTAMP)")
    private LocalDateTime time;

    @Column(columnDefinition = "TEXT NOT NULL")
    @ApiModelProperty("review text")
    private String text;

    @Column(columnDefinition = "INT DEFAULT 0")
    @ApiModelProperty("review rating")
    private int rating;

    @OneToMany(mappedBy = "likeReview")
    @JsonIgnore
    private List<BookReviewLike> likes;

    @ManyToOne
    @JoinColumn(name = "book_id", nullable = false, insertable = false, updatable = false)
    @JsonIgnore
    private Book reviewBook;

    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
    @JsonIgnore
    private User reviewUser;

    public Book getReviewBook() {
        return reviewBook;
    }

    public void setReviewBook(Book reviewBook) {
        this.reviewBook = reviewBook;
    }

    public User getReviewUser() {
        return reviewUser;
    }

    public void setReviewUser(User reviewUser) {
        this.reviewUser = reviewUser;
    }

    public List<BookReviewLike> getLikes() {
        return likes;
    }

    public void setLikes(List<BookReviewLike> likes) {
        this.likes = likes;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getBookId() {
        return bookId;
    }

    public void setBookId(int bookId) {
        this.bookId = bookId;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public LocalDateTime getTime() {
        return time;
    }

    public void setTime(LocalDateTime time) {
        this.time = time;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public int getRating() {
        return rating;
    }

    public void setRating(int rating) {
        this.rating = rating;
    }
}
