package com.bookshop.BookShopApp.structure.book.review;

import com.bookshop.BookShopApp.structure.user.User;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "message")
@ApiModel(description = "entity representing a message")
public class Message {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("message id generated by db automatically")
    private int id;

    @Column(columnDefinition = "TIMESTAMP NOT NULL")
    @ApiModelProperty("message date and time")
    private LocalDateTime time;

    @Column(name="user_id", columnDefinition = "INT")
    @ApiModelProperty("message user id from table users")
    private int userId;

    @Column(columnDefinition = "VARCHAR(255)")
    @ApiModelProperty("message not authorized user E-mail")
    private String email;

    @Column(columnDefinition = "VARCHAR(255)")
    @ApiModelProperty("message not authorized user name")
    private String name;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("message subject")
    private String subject;

    @Column(columnDefinition = "TEXT NOT NULL")
    @ApiModelProperty("message text")
    private String text;

    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
    @JsonIgnore
    private User messageUser;

    public User getMessageUser() {
        return messageUser;
    }

    public void setMessageUser(User messageUser) {
        this.messageUser = messageUser;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public LocalDateTime getTime() {
        return time;
    }

    public void setTime(LocalDateTime time) {
        this.time = time;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }
}
