package com.bookshop.BookShopApp.structure.tag;

import com.bookshop.BookShopApp.structure.enums.TagType;
import com.bookshop.BookShopApp.structure.book.Book;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.util.List;

@Entity
@Table(name = "tag")
@ApiModel(description = "entity representing a tag")
public class Tag {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("tag id generated by db automatically")
    private int id;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("Tag name")
    private String name;

    @Column(columnDefinition = "INT NOT NULL DEFAULT 0")
    @ApiModelProperty("count book by tag")
    private int count_book;

    @ApiModelProperty("tag class (for html/css)")
    private TagType type;

    @ManyToMany(mappedBy = "tags")
    @JsonIgnore
    private List<Book> books;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getCount_book() {
        return count_book;
    }

    public void setCount_book(int count_book) {
        this.count_book = count_book;
    }

    public TagType getType() {
        return type;
    }

    public void setType(TagType type) {
        this.type = type;
    }
}
