package com.bookshop.BookShopApp.structure.genre;

import com.bookshop.BookShopApp.structure.book.Book;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.util.List;

@Entity
@Table(name = "genre")
@ApiModel(description = "entity representing a genre")
public class Genre {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("genre id generated by db automatically")
    @JsonProperty("id")
    private int id;

    @Column(columnDefinition = "INT")
    @ApiModelProperty("parent genre id")
    @JsonProperty("parentId")
    private int parentId;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("mnemonic identity sequence of characters")
    private String slug;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("Genre name")
    @JsonProperty("name")
    private String name;

    @Column(columnDefinition = "INT NOT NULL DEFAULT 0")
    @ApiModelProperty("count book by genre")
    @JsonProperty("count_book")
    private int count_book;

    @ManyToMany(mappedBy = "genres")
    @JsonIgnore
    private List<Book> books;

    public int getCount_book() {
        return count_book;
    }

    public void setCount_book(int count_book) {
        this.count_book = count_book;
    }

    public List<Book> getBooks() {
        return books;
    }

    public void setBooks(List<Book> books) {
        this.books = books;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getParentId() {
        return parentId;
    }

    public void setParentId(int parentId) {
        this.parentId = parentId;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
